var availableTags = [
      "aerosol cans",
      "aluminum",
      "aluminum foil",
      "aluminum food cans",
      "aluminum pie plates",
      "aluminum trays",
      "tray",
      "trays",
      "ferrous metals",
      "metal paint cans",
      "metal tags",
      "nonferrous metals",
      "refrigerators",
      "steel",
      "steel cans",
      "steel lids",
      "aluminum lids",
      "glass",
      "car batteries",
      "lithium-ion batteries",
      "alkaline batteries",
      "lithium batteries",
      "washer/dryers",
      "washer",
      "dryer",
      "lacquer",
      "latex paint",
      "latex",
      "paint",
      "lead",
      "lead paint chips",
      "paint chips",
      "lead paint",
      "oil-based paint",
      "paint strippers",
      "paint thinners",
      "varnish",
      "wood",
      "wood stains",
      "corrugated cardboard",
      "cardboard",
      "drink",
      "drinks",
      "boxes",
      "drink boxes",
      "envelopes",
      "magazines",
      "mixed paper",
      "paper",
      "multi-wall paper bags",
      "bag",
      "bags",
      "newspaper",
      "office paper",
      "paper cups",
      "cups",
      "cup",
      "clamshells",
      "compostable",
      "pesticide",
      "container",
      "containers",
      "plastic egg cartons",
      "glue sticks",
      "garden tools",
      "tools",
      "jugs",
      "caps",
      "packing",
      "toothbrushes",
      "plastic peanuts",
      "peanuts",
      "medication",
      "containers",
      "six-pack rings",
      "rings",
      "buckets",
      "paint cans",
      "plastic paint cans",
      "Tyvek envelopes",
      "cartons",
      "plastic playsets",
      "playsets",
      "beverage",
      "film",
      "paper labels",
      "paper sleeves",
      "paperback books",
      "cd cases",
      "motor oil containers",
      "plastic cards",
      "plastic plant materials",
      "water filters",
      "asphalt",
      "ceramic tile",
      "contaminated wood",
      "household furniture",
      "mattresses",
      "roofing materials",
      "tile",
      "brick",
      "concrete",
      "dirt",
      "light fixtures",
      "neon lights",
      "sand",
      "carpet",
      "construction debris",
      "doors",
      "lighting ballasts",
      "office furniture",
      "sawdust",
      "windows",
      "carpet padding",
      "construction materials",
      "gypsum drywall",
      "linoleum",
      "pallets",
      "shingles",
      "ceiling tiles",
      "contaminated soil",
      "hardware",
      "lumber",
      "porcelain products",
      "stone",
      "wood furnishings",
      "audio equipment",
      "cassette players",
      "cell phones",
      "curling irons",
      "DVDs",
      "hard drives",
      "laptop computers",
      "microwaves",
      "power tools",
      "scanners",
      "toasters",
      "VCRs",
      "blu-ray players",
      "cassette tapes",
      "computer",
      "dehumidifiers",
      "electronic servers",
      "home electronics",
      "LCD Computer Monitor",
      "MP3 Players",
      "printers",
      "small appliances",
      "toner cartridges",
      "video game cartridges",
      "boomboxes",
      "CD players",
      "desktop computers",
      "floppy disks",
      "hoverboards",
      "LCD televisions",
      "office machines",
      "projectors",
      "tablets",
      "two-way radios",
      "video game",
      "cables",
      "CDs",
      "CRT",
      "digital cameras",
      "game consoles",
      "humidifiers",
      "medical equipment",
      "pagers",
      "receivers",
      "telephones",
      "typewriters",
      "video tapes",
      "calculators",
      "cell phone accessories",
      "CRT Televisions",
      "DVD players",
      "GPS Systems",
      "inkjet cartridges",
      "paper shredders",
      "record players",
      "television accessories",
      "vacuum cleaners",
      "vinyl records",
      "branches",
      "hay",
      "antifreeze",
      "car batteries",
      "hydraulic fluid",
      "oil filters",
      "transmission fluid",
      "auto bodies",
      "car fluids",
      "innertubes",
      "power steering fluid",
      "truck tires",
      "auto parts",
      "engine degreasers",
      "marine batteries",
      "radiators",
      "vehicles",
      "bike tires",
      "gas/oil mixture",
      "motor oil",
      "road flares",
      "brake fluid",
      "gasoline",
      "motor oil containers",
      "tires",
      "adult toys",
      "toys",
      "barbeque grills",
      "carpet padding",
      "clothing",
      "crayons",
      "freezers",
      "hair dye",
      "lighter fluid",
      "pizza boxes",
      "synthetic cork",
      "trophies",
      "bicycles",
      "controlled substances",
      "drink pouches",
      "hair spray",
      "inancdescent lightbulbs",
      "linens",
      "nail polish",
      "shoes",
      "tennis balls",
      "acids",
      "fertilizers",
      "gas cylinders",
      "herbicides",
      "items containing mercury",
      "oil filters",
      "solvents",
      "adhesives",
      "asbestos",
      "CFLs",
      "fire extinguishers",
      "HHW",
      "kerosene",
      "lice shampoo",
      "medical sharps",
      "nail polish removers",
      "fluorescent tubes",
      "pool chemicals",
      "sealers",
      "air conditioners",
      "exit signs",
      "ammunition",
      "explosives",
      "fungicides",
      "insecticides",
      "perfumes",
      "propane tanks",
      "smoke detectors",
      "x-rays",
      "bike tires",
      "chemistry sets",
      "cooking oil",
      "eyeglasses",
      "gift bags",
      "halogen bulbs",
      "kerosene",
      "plastic furniture",
      "sporting goods",
      "yoga mats",
      "arts and crafts supplies",
      "candy wrappers",
      "chip bags",
      "cookware",
      "fabric",
      "heaters",
      "latex foam pillows",
      "metal clothes hangers",
      "office supplies",
      "string lights",
      "toothpaste tubes",
      "baby products",
      "cigarettes",
      "corks",
      "flip-flops",
      "hair",
      "household cleaners",
      "lice shampoo",
      "musical instruments",
      "ornaments",
      "surfboards",
      "organic food waste",
      "yard waste",
      "brush",
      "holiday greens",
      "stumps",
      "christmas trees",
      "leaves",
      "weeds",
      "dirt",
      "manure",
      "wood",
      "grass clippings",
      "non-organic food waste",
      "wood chips",
      "books",
      "paperboard",
      "phone books",
      "bottles",
      "bottle",
      "cans",
      "metal",
      "metals",
      "plastic",
      "plastics",
      "battery",
      "batteries",
];
